name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: library/package-lock.json
    - name: Install dependencies
      run: npm install
      working-directory: library
    - name: Run unit tests
      run: npm run test:unit
      working-directory: library
    - name: Display softuni username
      run: echo 'vikix'
      working-directory: library
      
  build_and_run_ui_tests:
    needs: build_and_run_unit_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: library/package-lock.json
    - name: Install dependencies
      run: npm install
      working-directory: library
    - name: Install playwright
      run: npx playwright install
      working-directory: library
    - name: Run the app
      run: npm run start &
      working-directory: library
    - name: Run UI tests
      run: npm run test:ui
      working-directory: library
